<a href="https://colab.research.google.com/github/Priyanshi614/ML_SEM_6/blob/main/ML_Lab04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch
import torch.nn as nn

#A tensor is a number, vector, matrix or any n-dimensional array.

inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],[69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69,96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96,70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]],dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

inputs, targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [ ]:
from torch.utils.data import TensorDataset, DataLoader
import torch.nn.functional as F

In [ ]:
dataset = TensorDataset(inputs,targets)
dataset[0]

(tensor([73., 67., 43.]), tensor([56., 70.]))

In [ ]:
dataloader = DataLoader(dataset,batch_size=15, shuffle=True)
model = nn.Linear(in_features=3, out_features=2, bias=True)
optimizer = torch.optim.SGD(model.parameters(), 0.0001)


In [ ]:
# Loss function - torch.nn.functional.mse_loss
loss_fn = F.mse_loss

In [ ]:
def fit(num_epochs:int, model, loss_fn, optimizer):
  for epoch in range(num_epochs):
    batch = 0
    for xb,yb in dataloader:
      batch += 1
      pred = model(xb)
      loss = loss_fn(pred, yb)
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      print('epoch {} batch {} batch size {} loss {}'.format(epoch,batch,len(xb),loss.item()))

fit(1000, model, loss_fn, optimizer)

epoch 0 batch 1 batch size 15 loss 21015.267578125
epoch 1 batch 1 batch size 15 loss 13311.2978515625
epoch 2 batch 1 batch size 15 loss 8472.5234375
epoch 3 batch 1 batch size 15 loss 5428.53466796875
epoch 4 batch 1 batch size 15 loss 3509.41455078125
epoch 5 batch 1 batch size 15 loss 2295.8076171875
epoch 6 batch 1 batch size 15 loss 1525.146240234375
epoch 7 batch 1 batch size 15 loss 1032.9779052734375
epoch 8 batch 1 batch size 15 loss 716.2499389648438
epoch 9 batch 1 batch size 15 loss 510.3443298339844
epoch 10 batch 1 batch size 15 loss 374.7059631347656
epoch 11 batch 1 batch size 15 loss 283.8490905761719
epoch 12 batch 1 batch size 15 loss 221.72915649414062
epoch 13 batch 1 batch size 15 loss 178.22052001953125
epoch 14 batch 1 batch size 15 loss 146.91123962402344
epoch 15 batch 1 batch size 15 loss 123.72189331054688
epoch 16 batch 1 batch size 15 loss 106.04100799560547
epoch 17 batch 1 batch size 15 loss 92.18230438232422
epoch 18 batch 1 batch size 15 loss 81.04496

In [ ]:
new_data = torch.Tensor([[87, 134, 58], [102, 43, 37], [69, 96,70]])
new_targets = torch.Tensor([[119, 133], [22, 37], [103, 119]])
pred_new_data = model(new_data)
print("Predict (after training): ",new_targets,"\n", pred_new_data)

Predict (after training):  tensor([[119., 133.],
        [ 22.,  37.],
        [103., 119.]]) 
 tensor([[118.6864, 132.9567],
        [ 21.0764,  37.0138],
        [101.9269, 119.1395]], grad_fn=<AddmmBackward0>)
